# Generated by Django 3.0.7 on 2020-06-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200607_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a description', max_length=300),
            preserve_default=False,
        ),
    ]
