# Generated by Django 3.0.7 on 2020-06-13 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20200613_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=24)),
                ('last_name', models.CharField(max_length=24)),
                ('street_address_1', models.CharField(max_length=100)),
                ('apartment', models.CharField(blank=True, max_length=12, null=True)),
                ('country', models.CharField(choices=[('CA', 'CANADA'), ('US', 'AMERICA')], max_length=3)),
                ('province_or_state', models.CharField(blank=True, max_length=24, null=True)),
                ('postal_or_zip_code', models.CharField(blank=True, max_length=8, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ShippingDetails'),
        ),
    ]
