# Generated by Django 3.0.7 on 2020-06-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200615_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='images/items/main'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_caption',
            field=models.CharField(default='Product image.', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='images/items/thumbnails'),
        ),
    ]
