# Generated by Django 3.0.7 on 2020-06-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200616_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.CharField(choices=[('S', 'Shirts'), ('SW', 'Sports Wear'), ('OW', 'Outer Wear')], default='All', max_length=100),
            preserve_default=False,
        ),
    ]
