# Generated by Django 3.0.7 on 2020-06-17 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200617_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sub_category',
        ),
    ]
